name: Auto Generate Projects

on:
  schedule:
    - cron: "0 9 * * *"       # daily at 09:00 UTC
    - cron: "0 */5 * * *"     # every 5 hours
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Node (for JS tests)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack (Yarn/pnpm)
        run: corepack enable

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate next project
        env:
          PROVIDER: ${{ vars.PROVIDER || 'openai' }}
          MODEL_NAME: ${{ vars.MODEL_NAME || 'gpt-4o' }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_OWNER: miqdad-dev
          GITHUB_VISIBILITY: ${{ vars.GITHUB_VISIBILITY || 'public' }}
          ENABLE_DATA_FETCH: ${{ vars.ENABLE_DATA_FETCH || '1' }}
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          python scripts/generate_next.py
      
